### PR TITLE
Add missing po/LINGUAS file and drop Makefile.in.in

### LINKED ISSUE #20: indicator keyboard translation mistake
- Device: BQ E4.5
- Channel: rc
- Build: 2020-w15

Description:
even though the translation exists in the translation template the keyboard indicator does not take the value of the translation in the string of this "Text Entry Settings" and "Keyboard Layout"

Expected behavior:
The "Text Entry Settings" and "keyboard Layout" string takes the translation value of the language configured in the system.
ubuntu touch indicador teclado 20200412_095743068
imagen

### PR DESCRIPTION
**Pull request by dobey**
Fixes #20

### CODE REVIEW

**Review by Flohack74 — APPROVED** [review]

**Comment by Bolly** [comment]
Checked this on a BQM10FHD running RC 2020 W-33.
It works.
screenshot20200813_170352006

**Comment by farkasdvd** [comment]
Device: bq e5
Image: 2020-W35/2

Works as expected.
Probably not related but the Text Entry Settings opens a different Keyboard Layouts page than the one from System Settings > Language & Text > Keyboard Layouts. And changing the keyboard layout via the top bar doesn't seem to have any effect. Is this a know issue? If not, I can create a new issue with screenshots.

**Comment by dobey** [comment]
> And changing the keyboard layout via the top bar doesn't seem to have any effect. Is this a know issue?

The keyboard indicator is only for external keyboards, not the OSK.

**Comment by cibersheep** [comment]
Fix works  on E5HD RC

**Pull request merged**
